name: Validation

on:
  push:
    branches:
      - develop
      - feature/*
    tags:
      - v*.*.*

jobs:
  tests:
    name: "Run tests: ${{ matrix.browser }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: windows-latest
            browser: chromium
          - os: ubuntu-latest
            browser: firefox
          - os: macos-latest
            browser: webkit

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm

      - name: Set up Playwright cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install

      - name: Run tests
        run: npm run test -- --browser=${{ matrix.browser }}
        env:
          PUBLIC_WEBSITE_BASE_URL: https://example.org
          PUBLIC_APPLE_APP_STORE_URL: https://example.org#apple-store
          PUBLIC_GOOGLE_PLAY_STORE_URL: https://example.org#google-play
          PUBLIC_IOS_APP_ID: org.example.App
          PUBLIC_ANDROID_PACKAGE_NAME: org.example.app
          PUBLIC_ANDROID_CERTS_SHA256: sha256
