name: Validation

on:
  push:
    branches:
      - develop
      - feature/*
    tags:
      - v*.*.*

jobs:
  tests:
    name: "Test on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos
          - ubuntu
          - windows
    env:
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test -- --browser=all
        env:
          PUBLIC_WEBSITE_BASE_URL: https://example.org
          PUBLIC_APPLE_APP_STORE_URL: https://example.org#apple-store
          PUBLIC_GOOGLE_PLAY_STORE_URL: https://example.org#google-play
          PUBLIC_IOS_APP_ID: org.example.App
          PUBLIC_ANDROID_PACKAGE_NAME: org.example.app
          PUBLIC_ANDROID_CERTS_SHA256: sha256
